# config/meta.yml

meta_product_name: "Leasy"
meta_title: "Leasy - Automatisez votre gestion locative"
meta_description: "Leasy vous permet de gérer de manière automatique, fiable et efficace l'ensemble de vos dossiers de gestion locative."
meta_image: "cover.png"             # should exist in `app/assets/images/`
twitter_account: "@Planete_tech"   # required for Twitter Cards
